<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net10.0;net9.0;net8.0;net481;net48;net472;net471;net47;net462</TargetFrameworks>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <RepositoryType>github</RepositoryType>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <Description>SQLite configuration for AdaskoTheBeAsT.Dapper.NodaTime.</Description>
    <Authors>Adam "AdaskoTheBeAsT" Pluciński</Authors>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageProjectUrl>https://github.com/AdaskoTheBeAsT/AdaskoTheBeAsT.Dapper.NodaTime</PackageProjectUrl>
    <PackageTags>dapper;nodatime;sqlite</PackageTags>
  </PropertyGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net8.0'">
    <PackageReference Include="Microsoft.Data.Sqlite" Version="[8.0.27,9.0.0)" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="[2.1.12,3.0.0)" />
    <PackageReference Include="System.Text.Json" Version="[8.0.6,9.0.0)" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net9.0'">
    <PackageReference Include="Microsoft.Data.Sqlite" Version="[9.0.18,10.0.0)" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="[2.1.12,3.0.0)" />
    <PackageReference Include="System.Text.Json" Version="[9.0.18,10.0.0)" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net462' OR '$(TargetFramework)' == 'net47' OR '$(TargetFramework)' == 'net471' OR '$(TargetFramework)' == 'net472' OR '$(TargetFramework)' == 'net48' OR '$(TargetFramework)' == 'net481'  OR '$(TargetFramework)' == 'net10.0'">
    <PackageReference Include="Microsoft.Data.Sqlite" Version="[10.0.10,11.0.0)" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="[2.1.12,3.0.0)" />
    <PackageReference Include="System.Text.Json" Version="[10.0.10,11.0.0)" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFrameworkIdentifier)' == '.NETFramework'">
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="[1.0.3,2.0.0)" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AdaskoTheBeAsT.Dapper.NodaTime\AdaskoTheBeAsT.Dapper.NodaTime.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\..\LICENSE" Pack="true" PackagePath="" />
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
